CREATE TABLE aubmgecb_hodovka.tbl_users (
  ID INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  surname VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  secondname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  spare1 VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
  );